version: '3'
services:
  database:
    image: mysql:8.0
    container_name: teamd_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - teamd

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teamd-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
    command: >
      sh -c "sleep 10 &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    tty: true
    networks:
      - teamd

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
          - teamd
networks:
  teamd:
    driver: bridge
