version: '3'
services:
  database:
    image: mysql:8.0
    container_name: teamd_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - teamd

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - teamd

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teamd-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
    command: >
      sh -c "sleep 10 &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    tty: true
    networks:
      - teamd

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - backend
    networks:
      - teamd

  celery:
    container_name: celery
    build:
      context: .
    command: "celery -A backend.celery worker --loglevel=info --pool=solo"
    depends_on:
      - backend
      - rabbitmq
    volumes:
      - .:/app
    networks:
      - teamd

networks:
  teamd:
    driver: bridge
